[[redirects]]
  from = "/api/*"
  to = "https://site--sams-backend--zj5y5bs2dc2g.code.run/api/:splat"
  status = 200
  force = true

# Pass through CORS headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"